<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>RGBDS GB Z80 Assembly</string>
	<key>scopeName</key>
	<string>source.asm.gbz80</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>comment.block.gbz80</string>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.gbz80</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.line.gbz80</string>
			<key>match</key>
			<string>;.*$</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.line.alternative.gbz80</string>
			<key>match</key>
			<string>^\*.*$</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.double.gbz80</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.gbz80</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*((?i:set))\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.opcode.gbz80</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.other.opcode.gbz80</string>
			<key>match</key>
			<string>\b(?i:adc|add|and|bit|call|ccf|cp|cpl|daa|dec|di|ei|halt|inc|jp|jr|ld|ldh|nop|or|pop|push|res|ret|reti|rl|rla|rlc|rlca|rr|rra|rrc|rrca|rst|sbc|scf|sla|sra|srl|stop|sub|swap|xor)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.language.registercodes.gbz80</string>
			<key>match</key>
			<string>\b(?i:a|f|b|c|d|e|h|l|af|bc|de|hl|hli|hld|sp|pc|z|nz|nc)\b</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((?i:bank))\b(\s*\[)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.gbz80</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.gbz80</string>
			<key>match</key>
			<string>\b(?i:include|incbin|export|global|union|fragment|nextu|endu|printt|printv|printi|printf|fail|warn|if|elif|else|endc|purge|rept|endr|opt|popo|pusho|pops|pushs|equ|set|equs|macro|endm|shift|charmap|newcharmap|setcharmap|pushc|popc|rsreset|rsset|rb|rw|rl|db|dw|dl|ds|section|rom0|romx|vram|sram|wram0|wramx|oam|hram|align|load|endl)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.gbz80</string>
			<key>match</key>
			<string>\b(?i:mul|sin|cos|tan|asin|acos|atan|atan2|strcat|strcmp|strin|strlen|strlwr|strsub|strupr|bank|def|high|low|isconst)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.other.gbz80</string>
			<key>match</key>
			<string>\b((([a-zA-Z_][a-zA-Z_0-9]*)?\.)?[a-zA-Z_][a-zA-Z_0-9]*[:]{0,2})\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.decimal.gbz80</string>
			<key>match</key>
			<string>\b[0-9]+\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.hex.gbz80</string>
			<key>match</key>
			<string>\$[0-9a-fA-F]+\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.binary.gbz80</string>
			<key>match</key>
			<string>\%[01]+\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.octal.gbz80</string>
			<key>match</key>
			<string>\&amp;[0-7]+\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.gbgfx.gbz80</string>
			<key>match</key>
			<string>`[0-3]+\b</string>
		</dict>
	</array>
</dict>
</plist>
